create table tb_belonging (
    position integer,
    game_id bigint not null,
    list_id bigint not null,
    primary key (game_id, list_id)
);

create table tb_game (
    game_year integer,
    score float(53),
    id bigint generated by default as identity,
    genre varchar(255),
    img_url varchar(255),
    long_description TEXT,
    platforms varchar(255),
    short_description varchar(255),
    title varchar(255),
    primary key (id)
);

create table tb_game_list (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table if exists tb_belonging
add constraint FKrchwdikeu66uky1hf75ym1kh foreign key (list_id) references tb_game_list;

alter table if exists tb_belonging
add constraint FK2slybclee7wdfxhfltbvqkgpg foreign key (game_id) references tb_game;

INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');

INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Mass Effect Trilogy',
        4.8,
        2012,
        'Role-playing (RPG), Shooter',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png',
        'Comande a Normandy e salve a galáxia da ameaça dos Reapers.',
        'Mass Effect Trilogy é uma série de jogos de RPG e tiro em terceira pessoa desenvolvida pela BioWare. Acompanhe o Comandante Shepard em uma missão épica para unir civilizações galácticas contra uma ameaça ancestral conhecida como Reapers. Suas decisões moldam o destino da galáxia.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Red Dead Redemption 2',
        4.7,
        2018,
        'Role-playing (RPG), Adventure',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png',
        'Viva o Velho Oeste como Arthur Morgan, um fora da lei em fuga.',
        'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto da Rockstar Games. Situado em 1899, você vive como Arthur Morgan, membro da gangue Van der Linde, tentando sobreviver à queda do Velho Oeste em meio a conflitos internos e perseguições da lei.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'The Witcher 3: Wild Hunt',
        4.7,
        2014,
        'Role-playing (RPG), Adventure',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png',
        'Seja Geralt de Rívia em uma jornada épica por um mundo sombrio.',
        'The Witcher 3: Wild Hunt é um RPG de mundo aberto da CD Projekt Red. Você controla Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva, Ciri, enquanto enfrenta guerras, intrigas e criaturas místicas em um mundo rico e detalhado.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Sekiro: Shadows Die Twice',
        3.8,
        2019,
        'Role-playing (RPG), Adventure',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png',
        'Mestre shinobi em busca de vingança no Japão feudal.',
        'Sekiro: Shadows Die Twice é um jogo de ação e aventura da FromSoftware. Controlando um guerreiro shinobi, você deve resgatar seu mestre e vingar sua honra em um mundo brutal, com combates desafiadores, stealth e exploração intensa.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Ghost of Tsushima',
        4.6,
        2012,
        'Role-playing (RPG), Adventure',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png',
        'Lute pela liberdade de Tsushima contra a invasão mongol.',
        'Ghost of Tsushima é um jogo de ação e aventura em mundo aberto desenvolvido pela Sucker Punch. No papel de Jin Sakai, um samurai, você deve proteger sua terra da invasão mongol usando habilidades de combate tradicionais e furtividade como o Fantasma.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Super Mario World',
        4.7,
        1990,
        'Platform',
        'Super Ness, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png',
        'Mario e Luigi em uma nova aventura pelo Dino Island.',
        'Super Mario World é um clássico jogo de plataforma da Nintendo. Mario e Luigi devem resgatar a Princesa Peach e os amigos Yoshi dos vilões Bowser e seus filhos, enfrentando obstáculos, inimigos e fases criativas em uma jornada colorida.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Hollow Knight',
        4.6,
        2017,
        'Platform',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png',
        'Explore as ruínas de Hallownest em uma aventura desafiadora.',
        'Hollow Knight é um jogo de plataforma e ação no estilo metroidvania. Explore cavernas, cidades e ruínas em um vasto mundo subterrâneo, enfrentando criaturas bizarras e desvendando os mistérios de uma civilização caída.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Ori and the Blind Forest',
        4,
        2015,
        'Platform',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png',
        'Uma jornada tocante em um mundo mágico e vibrante.',
        'Ori and the Blind Forest é um jogo de plataforma com narrativa emocional e visuais deslumbrantes. Você controla Ori, um espírito guardião, em uma jornada comovente para restaurar a floresta de Nibel e descobrir seu verdadeiro destino.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Cuphead',
        4.6,
        2017,
        'Platform',
        'XBox, Playstation, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png',
        'Estilo retrô, tiroteio frenético e chefes memoráveis.',
        'Cuphead é um jogo de plataforma run and gun com gráficos inspirados nos desenhos dos anos 1930. Famoso pela dificuldade elevada, ele traz batalhas contra chefes criativos e jogabilidade intensa para um ou dois jogadores.'
    );

INSERT INTO
    tb_game (
        title,
        score,
        game_year,
        genre,
        platforms,
        img_url,
        short_description,
        long_description
    )
VALUES (
        'Sonic CD',
        4,
        1993,
        'Platform',
        'Sega CD, PC',
        'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png',
        'Viaje no tempo com Sonic para salvar o futuro de Little Planet.',
        'Sonic CD é um jogo de plataforma da SEGA com mecânica única de viagem no tempo. Sonic deve salvar Amy Rose e impedir os planos malignos do Dr. Robotnik, enfrentando novos inimigos e coletando Time Stones para mudar o futuro.'
    );

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (1, 1, 0);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (1, 2, 1);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (1, 3, 2);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (1, 4, 3);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (1, 5, 4);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (2, 6, 0);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (2, 7, 1);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (2, 8, 2);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (2, 9, 3);

INSERT INTO
    tb_belonging (list_id, game_id, position)
VALUES (2, 10, 4);create table tb_belonging (position integer, game_id bigint not null, list_id bigint not null, primary key (game_id, list_id));
create table tb_game (game_year integer, score float(53), id bigint generated by default as identity, genre varchar(255), img_url varchar(255), long_description TEXT, platforms varchar(255), short_description varchar(255), title varchar(255), primary key (id));
create table tb_game_list (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKrchwdikeu66uky1hf75ym1kh foreign key (list_id) references tb_game_list;
alter table if exists tb_belonging add constraint FK2slybclee7wdfxhfltbvqkgpg foreign key (game_id) references tb_game;
INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Comande a Normandy e salve a galáxia da ameaça dos Reapers.', 'Mass Effect Trilogy é uma série de jogos de RPG e tiro em terceira pessoa desenvolvida pela BioWare. Acompanhe o Comandante Shepard em uma missão épica para unir civilizações galácticas contra uma ameaça ancestral conhecida como Reapers. Suas decisões moldam o destino da galáxia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Viva o Velho Oeste como Arthur Morgan, um fora da lei em fuga.', 'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto da Rockstar Games. Situado em 1899, você vive como Arthur Morgan, membro da gangue Van der Linde, tentando sobreviver à queda do Velho Oeste em meio a conflitos internos e perseguições da lei.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Seja Geralt de Rívia em uma jornada épica por um mundo sombrio.', 'The Witcher 3: Wild Hunt é um RPG de mundo aberto da CD Projekt Red. Você controla Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva, Ciri, enquanto enfrenta guerras, intrigas e criaturas místicas em um mundo rico e detalhado.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Mestre shinobi em busca de vingança no Japão feudal.', 'Sekiro: Shadows Die Twice é um jogo de ação e aventura da FromSoftware. Controlando um guerreiro shinobi, você deve resgatar seu mestre e vingar sua honra em um mundo brutal, com combates desafiadores, stealth e exploração intensa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Lute pela liberdade de Tsushima contra a invasão mongol.', 'Ghost of Tsushima é um jogo de ação e aventura em mundo aberto desenvolvido pela Sucker Punch. No papel de Jin Sakai, um samurai, você deve proteger sua terra da invasão mongol usando habilidades de combate tradicionais e furtividade como o Fantasma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario e Luigi em uma nova aventura pelo Dino Island.', 'Super Mario World é um clássico jogo de plataforma da Nintendo. Mario e Luigi devem resgatar a Princesa Peach e os amigos Yoshi dos vilões Bowser e seus filhos, enfrentando obstáculos, inimigos e fases criativas em uma jornada colorida.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore as ruínas de Hallownest em uma aventura desafiadora.', 'Hollow Knight é um jogo de plataforma e ação no estilo metroidvania. Explore cavernas, cidades e ruínas em um vasto mundo subterrâneo, enfrentando criaturas bizarras e desvendando os mistérios de uma civilização caída.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma jornada tocante em um mundo mágico e vibrante.', 'Ori and the Blind Forest é um jogo de plataforma com narrativa emocional e visuais deslumbrantes. Você controla Ori, um espírito guardião, em uma jornada comovente para restaurar a floresta de Nibel e descobrir seu verdadeiro destino.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Estilo retrô, tiroteio frenético e chefes memoráveis.', 'Cuphead é um jogo de plataforma run and gun com gráficos inspirados nos desenhos dos anos 1930. Famoso pela dificuldade elevada, ele traz batalhas contra chefes criativos e jogabilidade intensa para um ou dois jogadores.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Viaje no tempo com Sonic para salvar o futuro de Little Planet.', 'Sonic CD é um jogo de plataforma da SEGA com mecânica única de viagem no tempo. Sonic deve salvar Amy Rose e impedir os planos malignos do Dr. Robotnik, enfrentando novos inimigos e coletando Time Stones para mudar o futuro.');
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);
create table tb_belonging (position integer, game_id bigint not null, list_id bigint not null, primary key (game_id, list_id));
create table tb_game (game_year integer, score float(53), id bigint generated by default as identity, genre varchar(255), img_url varchar(255), long_description TEXT, platforms varchar(255), short_description varchar(255), title varchar(255), primary key (id));
create table tb_game_list (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKrchwdikeu66uky1hf75ym1kh foreign key (list_id) references tb_game_list;
alter table if exists tb_belonging add constraint FK2slybclee7wdfxhfltbvqkgpg foreign key (game_id) references tb_game;
INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Comande a Normandy e salve a galáxia da ameaça dos Reapers.', 'Mass Effect Trilogy é uma série de jogos de RPG e tiro em terceira pessoa desenvolvida pela BioWare. Acompanhe o Comandante Shepard em uma missão épica para unir civilizações galácticas contra uma ameaça ancestral conhecida como Reapers. Suas decisões moldam o destino da galáxia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Viva o Velho Oeste como Arthur Morgan, um fora da lei em fuga.', 'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto da Rockstar Games. Situado em 1899, você vive como Arthur Morgan, membro da gangue Van der Linde, tentando sobreviver à queda do Velho Oeste em meio a conflitos internos e perseguições da lei.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Seja Geralt de Rívia em uma jornada épica por um mundo sombrio.', 'The Witcher 3: Wild Hunt é um RPG de mundo aberto da CD Projekt Red. Você controla Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva, Ciri, enquanto enfrenta guerras, intrigas e criaturas místicas em um mundo rico e detalhado.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Mestre shinobi em busca de vingança no Japão feudal.', 'Sekiro: Shadows Die Twice é um jogo de ação e aventura da FromSoftware. Controlando um guerreiro shinobi, você deve resgatar seu mestre e vingar sua honra em um mundo brutal, com combates desafiadores, stealth e exploração intensa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Lute pela liberdade de Tsushima contra a invasão mongol.', 'Ghost of Tsushima é um jogo de ação e aventura em mundo aberto desenvolvido pela Sucker Punch. No papel de Jin Sakai, um samurai, você deve proteger sua terra da invasão mongol usando habilidades de combate tradicionais e furtividade como o Fantasma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario e Luigi em uma nova aventura pelo Dino Island.', 'Super Mario World é um clássico jogo de plataforma da Nintendo. Mario e Luigi devem resgatar a Princesa Peach e os amigos Yoshi dos vilões Bowser e seus filhos, enfrentando obstáculos, inimigos e fases criativas em uma jornada colorida.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore as ruínas de Hallownest em uma aventura desafiadora.', 'Hollow Knight é um jogo de plataforma e ação no estilo metroidvania. Explore cavernas, cidades e ruínas em um vasto mundo subterrâneo, enfrentando criaturas bizarras e desvendando os mistérios de uma civilização caída.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma jornada tocante em um mundo mágico e vibrante.', 'Ori and the Blind Forest é um jogo de plataforma com narrativa emocional e visuais deslumbrantes. Você controla Ori, um espírito guardião, em uma jornada comovente para restaurar a floresta de Nibel e descobrir seu verdadeiro destino.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Estilo retrô, tiroteio frenético e chefes memoráveis.', 'Cuphead é um jogo de plataforma run and gun com gráficos inspirados nos desenhos dos anos 1930. Famoso pela dificuldade elevada, ele traz batalhas contra chefes criativos e jogabilidade intensa para um ou dois jogadores.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Viaje no tempo com Sonic para salvar o futuro de Little Planet.', 'Sonic CD é um jogo de plataforma da SEGA com mecânica única de viagem no tempo. Sonic deve salvar Amy Rose e impedir os planos malignos do Dr. Robotnik, enfrentando novos inimigos e coletando Time Stones para mudar o futuro.');
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);
create table tb_belonging (position integer, game_id bigint not null, list_id bigint not null, primary key (game_id, list_id));
create table tb_game (game_year integer, score float(53), id bigint generated by default as identity, genre varchar(255), img_url varchar(255), long_description TEXT, platforms varchar(255), short_description varchar(255), title varchar(255), primary key (id));
create table tb_game_list (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKrchwdikeu66uky1hf75ym1kh foreign key (list_id) references tb_game_list;
alter table if exists tb_belonging add constraint FK2slybclee7wdfxhfltbvqkgpg foreign key (game_id) references tb_game;
INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Comande a Normandy e salve a galáxia da ameaça dos Reapers.', 'Mass Effect Trilogy é uma série de jogos de RPG e tiro em terceira pessoa desenvolvida pela BioWare. Acompanhe o Comandante Shepard em uma missão épica para unir civilizações galácticas contra uma ameaça ancestral conhecida como Reapers. Suas decisões moldam o destino da galáxia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Viva o Velho Oeste como Arthur Morgan, um fora da lei em fuga.', 'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto da Rockstar Games. Situado em 1899, você vive como Arthur Morgan, membro da gangue Van der Linde, tentando sobreviver à queda do Velho Oeste em meio a conflitos internos e perseguições da lei.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Seja Geralt de Rívia em uma jornada épica por um mundo sombrio.', 'The Witcher 3: Wild Hunt é um RPG de mundo aberto da CD Projekt Red. Você controla Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva, Ciri, enquanto enfrenta guerras, intrigas e criaturas místicas em um mundo rico e detalhado.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Mestre shinobi em busca de vingança no Japão feudal.', 'Sekiro: Shadows Die Twice é um jogo de ação e aventura da FromSoftware. Controlando um guerreiro shinobi, você deve resgatar seu mestre e vingar sua honra em um mundo brutal, com combates desafiadores, stealth e exploração intensa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Lute pela liberdade de Tsushima contra a invasão mongol.', 'Ghost of Tsushima é um jogo de ação e aventura em mundo aberto desenvolvido pela Sucker Punch. No papel de Jin Sakai, um samurai, você deve proteger sua terra da invasão mongol usando habilidades de combate tradicionais e furtividade como o Fantasma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario e Luigi em uma nova aventura pelo Dino Island.', 'Super Mario World é um clássico jogo de plataforma da Nintendo. Mario e Luigi devem resgatar a Princesa Peach e os amigos Yoshi dos vilões Bowser e seus filhos, enfrentando obstáculos, inimigos e fases criativas em uma jornada colorida.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore as ruínas de Hallownest em uma aventura desafiadora.', 'Hollow Knight é um jogo de plataforma e ação no estilo metroidvania. Explore cavernas, cidades e ruínas em um vasto mundo subterrâneo, enfrentando criaturas bizarras e desvendando os mistérios de uma civilização caída.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma jornada tocante em um mundo mágico e vibrante.', 'Ori and the Blind Forest é um jogo de plataforma com narrativa emocional e visuais deslumbrantes. Você controla Ori, um espírito guardião, em uma jornada comovente para restaurar a floresta de Nibel e descobrir seu verdadeiro destino.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Estilo retrô, tiroteio frenético e chefes memoráveis.', 'Cuphead é um jogo de plataforma run and gun com gráficos inspirados nos desenhos dos anos 1930. Famoso pela dificuldade elevada, ele traz batalhas contra chefes criativos e jogabilidade intensa para um ou dois jogadores.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Viaje no tempo com Sonic para salvar o futuro de Little Planet.', 'Sonic CD é um jogo de plataforma da SEGA com mecânica única de viagem no tempo. Sonic deve salvar Amy Rose e impedir os planos malignos do Dr. Robotnik, enfrentando novos inimigos e coletando Time Stones para mudar o futuro.');
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);
create table tb_belonging (position integer, game_id bigint not null, list_id bigint not null, primary key (game_id, list_id));
create table tb_game (game_year integer, score float(53), id bigint generated by default as identity, genre varchar(255), img_url varchar(255), long_description TEXT, platforms varchar(255), short_description varchar(255), title varchar(255), primary key (id));
create table tb_game_list (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table if exists tb_belonging add constraint FKrchwdikeu66uky1hf75ym1kh foreign key (list_id) references tb_game_list;
alter table if exists tb_belonging add constraint FK2slybclee7wdfxhfltbvqkgpg foreign key (game_id) references tb_game;
INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Comande a Normandy e salve a galáxia da ameaça dos Reapers.', 'Mass Effect Trilogy é uma série de jogos de RPG e tiro em terceira pessoa desenvolvida pela BioWare. Acompanhe o Comandante Shepard em uma missão épica para unir civilizações galácticas contra uma ameaça ancestral conhecida como Reapers. Suas decisões moldam o destino da galáxia.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Viva o Velho Oeste como Arthur Morgan, um fora da lei em fuga.', 'Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto da Rockstar Games. Situado em 1899, você vive como Arthur Morgan, membro da gangue Van der Linde, tentando sobreviver à queda do Velho Oeste em meio a conflitos internos e perseguições da lei.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Seja Geralt de Rívia em uma jornada épica por um mundo sombrio.', 'The Witcher 3: Wild Hunt é um RPG de mundo aberto da CD Projekt Red. Você controla Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva, Ciri, enquanto enfrenta guerras, intrigas e criaturas místicas em um mundo rico e detalhado.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Mestre shinobi em busca de vingança no Japão feudal.', 'Sekiro: Shadows Die Twice é um jogo de ação e aventura da FromSoftware. Controlando um guerreiro shinobi, você deve resgatar seu mestre e vingar sua honra em um mundo brutal, com combates desafiadores, stealth e exploração intensa.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Lute pela liberdade de Tsushima contra a invasão mongol.', 'Ghost of Tsushima é um jogo de ação e aventura em mundo aberto desenvolvido pela Sucker Punch. No papel de Jin Sakai, um samurai, você deve proteger sua terra da invasão mongol usando habilidades de combate tradicionais e furtividade como o Fantasma.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Mario e Luigi em uma nova aventura pelo Dino Island.', 'Super Mario World é um clássico jogo de plataforma da Nintendo. Mario e Luigi devem resgatar a Princesa Peach e os amigos Yoshi dos vilões Bowser e seus filhos, enfrentando obstáculos, inimigos e fases criativas em uma jornada colorida.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Explore as ruínas de Hallownest em uma aventura desafiadora.', 'Hollow Knight é um jogo de plataforma e ação no estilo metroidvania. Explore cavernas, cidades e ruínas em um vasto mundo subterrâneo, enfrentando criaturas bizarras e desvendando os mistérios de uma civilização caída.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Uma jornada tocante em um mundo mágico e vibrante.', 'Ori and the Blind Forest é um jogo de plataforma com narrativa emocional e visuais deslumbrantes. Você controla Ori, um espírito guardião, em uma jornada comovente para restaurar a floresta de Nibel e descobrir seu verdadeiro destino.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Estilo retrô, tiroteio frenético e chefes memoráveis.', 'Cuphead é um jogo de plataforma run and gun com gráficos inspirados nos desenhos dos anos 1930. Famoso pela dificuldade elevada, ele traz batalhas contra chefes criativos e jogabilidade intensa para um ou dois jogadores.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Viaje no tempo com Sonic para salvar o futuro de Little Planet.', 'Sonic CD é um jogo de plataforma da SEGA com mecânica única de viagem no tempo. Sonic deve salvar Amy Rose e impedir os planos malignos do Dr. Robotnik, enfrentando novos inimigos e coletando Time Stones para mudar o futuro.');
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);
